# Default Root Certificate Authority
# ==================================
CA			:= ca/root

# Cryptographic Hash Function
# ===========================
# SHA1			For legacy applications. These will not be trusted publicly / on the internet.
# SHA256		Most commonly used as of today.
# ECC256		For those that need shorter keys with stronger security.
CHF			:= SHA256

# Default Distinguished Name
# ==========================
# COUNTRY		:= Country Name (2 letter code)
# STATE			:= State or Province Name (full name)
# LOCALITY		:= Locality Name (eg, city)
# ORGANIZATION		:= Organization Name (eg, company)
# ORGANIZATIONALUNIT	:= Organizational Unit Name (eg, section)
# EMAIL			:= Email Address

# Default Export Password
# =======================
PASSWORD		:= changeit
